# Generated by Django 3.2.7 on 2021-12-01 21:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('telefono_contacto', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('telefono_contacto_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+56900000000', max_length=128, null=True, region=None)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('prevision', models.CharField(max_length=50, verbose_name='Prevision')),
                ('domicilio', models.CharField(max_length=255, verbose_name='Prevision')),
                ('foto_perfil', models.ImageField(default='blank-profile-picture-973460_640.png', null=True, upload_to='Usuarios/', verbose_name='Foto de Perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_admin', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Paciente', 'PACIENTE'), ('Medico', 'MEDICO'), ('Administrativo', 'ADMINISTRATIVO')], default='Paciente', max_length=100, verbose_name='Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.usuario',),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.usuario',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.usuario',),
        ),
    ]
