# Generated by Django 3.2.7 on 2021-12-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=models.IntegerField(unique=True), max_length=9),
        ),
    ]
