# Generated by Django 3.2.7 on 2021-12-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(max_length=255, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='type',
            field=models.CharField(choices=[('Paciente', 'PACIENTE'), ('Medico', 'MEDICO'), ('Administrativo', 'ADMINISTRATIVO')], default='Paciente', max_length=100, verbose_name='Tipo de Usuario'),
        ),
    ]
