# Generated by Django 3.2.7 on 2021-12-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20211201_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Administrativo',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
