# Generated by Django 3.2.7 on 2021-12-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_usuario_fecha_de_alta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_de_alta',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateField(null=True, verbose_name='Fecha Ingreso al Sistema'),
        ),
    ]
