# Generated by Django 3.2.7 on 2021-12-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20211206_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
