# Generated by Django 3.2.7 on 2021-12-06 04:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_usuario_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso al Sistema'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='prevision',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prevision'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_contacto_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
    ]
