# Generated by Django 3.2.7 on 2021-12-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20211206_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.usuario',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='type',
            field=models.CharField(choices=[('Paciente', 'PACIENTE'), ('Medico', 'MEDICO'), ('Administrativo', 'ADMINISTRATIVO')], default='Paciente', max_length=100, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='blank-profile-picture-973460_640.png', null=True, upload_to='Usuarios/', verbose_name='Foto de Perfil'),
        ),
    ]
