# Generated by Django 3.2.7 on 2021-12-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.usuario',),
        ),
    ]
