# Generated by Django 3.2.7 on 2021-12-01 21:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono_contacto', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('tipo_contacto', models.IntegerField(choices=[[0, 'RADIOTERAPIA'], [1, 'RADIOCIRUGÍA'], [2, 'BRAQUITERAPIA'], [3, 'FOTODINAMIA'], [4, 'OTROS']])),
                ('mensaje', models.TextField()),
                ('paciente_contactado', models.BooleanField(default=False)),
                ('fecha_contacto', models.DateField(null=True)),
            ],
        ),
    ]
