# Generated by Django 3.2.7 on 2021-11-30 03:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha_contacto',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='paciente_contactado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='telefono_contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+56900000000', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
