# Generated by Django 3.2.7 on 2021-10-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img_perfil',
            field=models.ImageField(null='blank-profile-picture-973460_640.png', upload_to='Usuarios'),
            preserve_default='blank-profile-picture-973460_640.png',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(unique=True),
        ),
    ]
