# Generated by Django 3.2.7 on 2021-11-30 04:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20211130_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(default='', max_length=255, verbose_name='Prevision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='prevision',
            field=models.CharField(default='', max_length=50, verbose_name='Prevision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_contacto_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+56900000000', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
