# Generated by Django 3.2.7 on 2021-10-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_usuario_img_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('tipo_contacto', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencia'], [3, 'Felicitaciones']])),
                ('mensaje', models.TextField()),
                ('avisis', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
