# Generated by Django 3.2.7 on 2021-10-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20211025_2354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Formulario_Contacto',
        ),
        migrations.RenameField(
            model_name='formulario_contacto',
            old_name='avisis',
            new_name='avisos',
        ),
    ]
