# Generated by Django 3.2.7 on 2021-10-26 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20211025_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario_contacto',
            name='avisos',
        ),
    ]
