# Generated by Django 3.2.7 on 2021-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_rename_formulario_contacto_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.IntegerField()),
                ('img_perfil', models.ImageField(default='blank-profile-picture-973460_640.png', upload_to='Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipo_contacto',
            field=models.IntegerField(choices=[[0, 'RADIOTERAPIA'], [1, 'RADIOCIRUGÍA'], [2, 'BRAQUITERAPIA'], [3, 'FOTODINAMIA'], [4, 'OTROS']]),
        ),
    ]
